# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 22:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgreementAcceptance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AgreementVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('content', models.TextField()),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal.Agreement')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='agreementacceptance',
            name='agreement_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal.AgreementVersion'),
        ),
        migrations.AddField(
            model_name='agreementacceptance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='agreementversion',
            unique_together=set([('agreement', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='agreementacceptance',
            unique_together=set([('user', 'agreement_version', 'date')]),
        ),
    ]
